@extends('layouts.app')
@section('title', 'Etheria Beauty | Beauty services')
@section('content')
<main>
<section class="mx-auto grid max-w-7xl gap-10 px-6 pb-24 pt-12 lg:grid-cols-[1fr_0.82fr] lg:items-center lg:px-10 lg:pt-20"><div class="fade-in"><p class="eyebrow mb-6">Beauty, your way</p><h1 class="display max-w-3xl">Etheria<br><span class="text-[#a66362]">Beauty.</span></h1><p class="mt-8 max-w-md text-base leading-7 text-[#746965]">A considered beauty experience, with room for you to feel completely yourself.</p><p class="mt-3 text-sm italic text-[#a66362]">{{ config('etheria.slogan') }}</p><div class="mt-9 flex flex-wrap gap-3"><a class="btn-primary rounded-full px-6 py-4 text-sm font-bold" href="{{ route('booking.create') }}">Book an appointment <span class="ml-2">↗</span></a><a class="btn-outline rounded-full px-6 py-4 text-sm font-bold" href="{{ $whatsappUrl }}" target="_blank">Chat via WhatsApp</a></div></div><div class="relative min-h-[420px] overflow-hidden rounded-[2rem] bg-[#d6b8af] lg:min-h-[570px]"><div class="absolute inset-0 bg-[radial-gradient(circle_at_65%_25%,#f9e9df_0,transparent_33%),linear-gradient(145deg,#c99b91,#ecd8ce)]"></div><div class="absolute bottom-8 left-8 border-l border-white/70 pl-4 text-white"><p class="font-serif text-4xl">Your ritual<br>starts here.</p><p class="mt-2 text-xs uppercase tracking-[.2em]">Image placeholder</p></div></div></section>
<section id="services" class="bg-white px-6 py-24 lg:px-10"><div class="mx-auto max-w-7xl"><div class="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p class="eyebrow">The menu</p><h2 class="mt-3 font-serif text-5xl">Services made personal.</h2></div><p class="max-w-sm text-sm leading-6 text-[#746965]">Choose your service, find a time that suits you, and let the rest unfold.</p></div><div class="mt-14 grid gap-4 md:grid-cols-3">@foreach($services as $service)<article class="border border-[#e6d9d3] p-7 transition hover:-translate-y-1 hover:border-[#a66362]"><div class="flex items-start justify-between gap-4"><h3 class="font-serif text-3xl">{{ $service->name }}</h3><span class="text-sm font-bold text-[#a66362]">IDR {{ number_format($service->price, 0, ',', '.') }}</span></div><p class="mt-8 text-sm leading-6 text-[#746965]">{{ $service->description }}</p><a class="mt-8 inline-block text-sm font-bold underline decoration-[#a66362] underline-offset-4" href="{{ route('booking.create', ['service' => $service->id]) }}">Choose this service</a></article>@endforeach</div></div></section>
<section id="about" class="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-[.7fr_1fr] lg:px-10"><p class="eyebrow">About Etheria</p><div><h2 class="font-serif text-5xl">A space for your<br><span class="text-[#a66362]">beauty ritual.</span></h2><p class="mt-8 max-w-xl leading-8 text-[#746965]">{{ config('etheria.description') }}</p></div></section>
<section id="gallery" class="bg-[#efe4de] px-6 py-24 lg:px-10"><div class="mx-auto max-w-7xl"><p class="eyebrow">The gallery</p><h2 class="mt-3 font-serif text-5xl">A glimpse of Etheria.</h2><div class="mt-12 grid gap-4 md:grid-cols-3">@forelse($gallery as $item)<div class="aspect-[4/5] overflow-hidden bg-[#d6b8af]"><img src="{{ Storage::url($item->image_path) }}" alt="{{ $item->title }}" loading="lazy" class="h-full w-full object-cover"></div>@empty @foreach(['Clinic / room','Treatment results','Before / after'] as $label)<div class="flex aspect-[4/5] items-end bg-[#d6b8af] p-6 text-white"><div><p class="font-serif text-3xl">{{ $label }}</p><p class="mt-2 text-xs uppercase tracking-[.18em]">Image placeholder</p></div></div>@endforeach @endforelse</div></div></section>
<section class="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div class="grid gap-12 lg:grid-cols-2"><div><p class="eyebrow">Visit us</p><h2 class="mt-3 font-serif text-5xl">Make time<br>for yourself.</h2><p class="mt-8 text-[#746965]">{{ config('etheria.address') }}</p><a href="{{ config('etheria.maps_url') }}" class="mt-5 inline-block font-bold underline decoration-[#a66362] underline-offset-4">Get directions ↗</a></div><div class="border-l border-[#e6d9d3] pl-8"><p class="eyebrow">Testimonials</p>@forelse($testimonials as $item)<blockquote class="mt-6 font-serif text-3xl">“{{ $item->quote }}”<footer class="mt-5 font-sans text-sm text-[#746965]">{{ $item->customer_name }}</footer></blockquote>@empty<p class="mt-6 text-[#746965]">[CUSTOMER TESTIMONIAL WILL BE ADDED HERE.]</p>@endforelse</div></div></section>
</main>
@endsection